version: 2.1
orbs:
  architect: giantswarm/architect@4.35.5

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  integration-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-integration
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.1
          helm-version: v3.8.2
          kubernetes-version: v1.21.1
      - run:
          name: "Setup test tools"
          command: bash scripts/setup-test-tools.sh
      - run:
          name: "Run acceptance tests"
          command: CGO_ENABLED=0 make test-acceptance


workflows:
  test-and-push:
    jobs:
      - unit-tests:
          filters:
            tags:
              only: /^v.*/
      - integration-tests:
          filters:
            tags:
              only: /^v.*/
      - acceptance-tests:
          filters:
            tags:
              only: /^v.*/
      - architect/go-build:
          context: architect
          name: go-build
          binary: fleet-membership-operator-gcp
          resource_class: xlarge
          requires:
            - unit-tests
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "fleet-membership-operator-gcp"
          requires:
            - push-to-registries
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-to-gcp-app-collection
          app_name: "fleet-membership-operator-gcp"
          app_collection_repo: "gcp-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
