apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
    {{- include "labels.selector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/.gcp/credentials
          command:
            - /manager
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 80Mi
          volumeMounts:
            - name: credentials
              mountPath: "home/.gcp"
              readOnly: true
      volumes:
        - name: credentials
          secret:
            secretName: {{ include "resource.default.name" . }}-gcp-credentials
